[package]
name = "refract-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
compio.workspace = true
metrics.workspace = true
ordered-float.workspace = true
rand.workspace = true
strum.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
