[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
clap.workspace = true
refract-loadgen = { path = "../crates/refract-loadgen" }
refract-signal = { path = "../crates/refract-signal" }
refract-xdp = { path = "../crates/refract-xdp" }
xshell.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[[bin]]
name = "xtask"
path = "src/main.rs"
