//! Defensive RTCP compound packet parsing and bounded packet generation.
//!
//! Compound packets are capped at 1500 bytes. The parser validates each RTCP
//! length field before exposing borrowed packet bodies.
//!
//! # Examples
//!
//! ```
//! # use refract_rtp::rtcp::{RtcpBuilder, RtcpCompound};
//! let mut builder = RtcpBuilder::new();
//! builder.push_bye(7)?;
//! let packets = RtcpCompound::parse(builder.as_slice())?.collect::<Result<Vec<_>, _>>()?;
//! assert_eq!(packets.len(), 1);
//! # Ok::<(), refract_rtp::RtpError>(())
//! ```

use crate::{
    RtpError, Stability,
    error::{RtcpErrorReason, RtpResult},
    header::{read_u16, read_u32, write_u16, write_u32},
};

/// Maximum RTCP compound packet length accepted or generated by this crate.
pub const MAX_RTCP_COMPOUND_LEN: usize = 1_500;

const RTCP_HEADER_LEN: usize = 4;
const RTCP_VERSION: u8 = 2;
const VERSION_SHIFT: u8 = 6;
const COUNT_MASK: u8 = 0x1f;
const PT_SR: u8 = 200;
const PT_RR: u8 = 201;
const PT_SDES: u8 = 202;
const PT_BYE: u8 = 203;
const PT_APP: u8 = 204;
const PT_RTPFB: u8 = 205;
const PT_PSFB: u8 = 206;
const PT_XR: u8 = 207;
const FMT_NACK: u8 = 1;
const FMT_TRANSPORT_CC: u8 = 15;
const FMT_PLI: u8 = 1;
const FMT_FIR: u8 = 4;
const FMT_REMB: u8 = 15;

/// Borrowed RTCP compound packet iterator.
#[derive(Debug, Clone)]
pub struct RtcpCompound<'a> {
    remaining: &'a [u8],
}

impl<'a> RtcpCompound<'a> {
    /// Parses an RTCP compound packet into an iterator.
    ///
    /// # Errors
    ///
    /// Returns an error when the compound packet is empty, exceeds 1500 bytes,
    /// or is shorter than one RTCP common header.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::{RtcpBuilder, RtcpCompound};
    /// let mut builder = RtcpBuilder::new();
    /// builder.push_bye(9)?;
    /// assert_eq!(RtcpCompound::parse(builder.as_slice())?.count(), 1);
    /// # Ok::<(), refract_rtp::RtpError>(())
    /// ```
    pub const fn parse(bytes: &'a [u8]) -> RtpResult<Self> {
        if bytes.len() > MAX_RTCP_COMPOUND_LEN {
            return Err(RtpError::RtcpCompoundTooLarge {
                len: bytes.len(),
                max: MAX_RTCP_COMPOUND_LEN,
            });
        }
        if bytes.len() < RTCP_HEADER_LEN {
            return Err(RtpError::RtcpPacketTooShort { len: bytes.len() });
        }
        Ok(Self { remaining: bytes })
    }

    /// Returns the Stage 1 stability marker for this public API.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::{rtcp::{RtcpBuilder, RtcpCompound}, Stability};
    /// let mut builder = RtcpBuilder::new();
    /// builder.push_bye(9)?;
    /// assert_eq!(
    ///     RtcpCompound::parse(builder.as_slice())?.stability(),
    ///     Stability::Stage1
    /// );
    /// # Ok::<(), refract_rtp::RtpError>(())
    /// ```
    #[must_use]
    pub const fn stability(&self) -> Stability {
        Stability::Stage1
    }
}

impl<'a> Iterator for RtcpCompound<'a> {
    type Item = RtpResult<RtcpPacket<'a>>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.remaining.is_empty() {
            return None;
        }
        if self.remaining.len() < RTCP_HEADER_LEN {
            let len = self.remaining.len();
            self.remaining = &[];
            return Some(Err(RtpError::RtcpPacketTooShort { len }));
        }
        let first = self.remaining[0];
        let version = first >> VERSION_SHIFT;
        if version != RTCP_VERSION {
            self.remaining = &[];
            return Some(Err(RtpError::InvalidVersion { version }));
        }
        let count = first & COUNT_MASK;
        let packet_type = self.remaining[1];
        let words = read_u16(&self.remaining[2..4]);
        let declared = (usize::from(words) + 1) * 4;
        if declared > self.remaining.len() {
            let remaining = self.remaining.len();
            self.remaining = &[];
            return Some(Err(RtpError::RtcpLengthTooLarge {
                declared,
                remaining,
            }));
        }
        let (packet, tail) = self.remaining.split_at(declared);
        self.remaining = tail;
        Some(parse_packet(count, packet_type, &packet[RTCP_HEADER_LEN..]))
    }
}

/// Parsed RTCP packet.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum RtcpPacket<'a> {
    /// Sender Report.
    SenderReport(SenderReport),
    /// Receiver Report.
    ReceiverReport(ReceiverReport<'a>),
    /// Source description packet.
    Sdes {
        /// SDES chunk count.
        count: u8,
        /// Raw SDES chunk bytes.
        chunks: &'a [u8],
    },
    /// Goodbye packet.
    Bye {
        /// SSRC/CSRC count.
        count: u8,
        /// Raw BYE body.
        body: &'a [u8],
    },
    /// Application-defined packet.
    App {
        /// APP subtype.
        subtype: u8,
        /// APP body.
        body: &'a [u8],
    },
    /// RTP feedback packet.
    Rtpfb(RtpFeedback<'a>),
    /// Payload-specific feedback packet.
    Psfb(PayloadFeedback<'a>),
    /// Extended report packet.
    Xr {
        /// Sender SSRC.
        sender_ssrc: u32,
        /// Raw XR report blocks.
        blocks: &'a [u8],
    },
}

impl RtcpPacket<'_> {
    /// Returns the Stage 1 stability marker for this public API.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::{RtcpBuilder, RtcpCompound};
    /// let mut builder = RtcpBuilder::new();
    /// builder.push_bye(9)?;
    /// let packet = RtcpCompound::parse(builder.as_slice())?
    ///     .next()
    ///     .transpose()?;
    /// assert_eq!(
    ///     packet.map(|item| item.stability()),
    ///     Some(refract_rtp::Stability::Stage1)
    /// );
    /// # Ok::<(), refract_rtp::RtpError>(())
    /// ```
    #[must_use]
    pub const fn stability(self) -> Stability {
        Stability::Stage1
    }
}

/// RTCP Sender Report fields.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SenderReport {
    /// Sender SSRC.
    pub sender_ssrc: u32,
    /// NTP timestamp most-significant word.
    pub ntp_msw: u32,
    /// NTP timestamp least-significant word.
    pub ntp_lsw: u32,
    /// RTP timestamp.
    pub rtp_timestamp: u32,
    /// Sender packet count.
    pub packet_count: u32,
    /// Sender octet count.
    pub octet_count: u32,
}

impl SenderReport {
    /// Returns the Stage 1 stability marker for this public API.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::SenderReport;
    /// let sr = SenderReport {
    ///     sender_ssrc: 1,
    ///     ntp_msw: 0,
    ///     ntp_lsw: 0,
    ///     rtp_timestamp: 0,
    ///     packet_count: 0,
    ///     octet_count: 0,
    /// };
    /// assert_eq!(sr.stability(), refract_rtp::Stability::Stage1);
    /// ```
    #[must_use]
    pub const fn stability(self) -> Stability {
        Stability::Stage1
    }
}

/// RTCP Receiver Report body.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReceiverReport<'a> {
    /// Sender SSRC.
    pub sender_ssrc: u32,
    /// Raw 24-byte report blocks.
    pub reports: &'a [u8],
}

impl ReceiverReport<'_> {
    /// Returns the Stage 1 stability marker for this public API.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::ReceiverReport;
    /// let rr = ReceiverReport {
    ///     sender_ssrc: 1,
    ///     reports: &[],
    /// };
    /// assert_eq!(rr.stability(), refract_rtp::Stability::Stage1);
    /// ```
    #[must_use]
    pub const fn stability(self) -> Stability {
        Stability::Stage1
    }
}

/// Parsed RTP feedback packet.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum RtpFeedback<'a> {
    /// Generic NACK feedback.
    Nack {
        /// Packet sender SSRC.
        sender_ssrc: u32,
        /// Media source SSRC.
        media_ssrc: u32,
        /// Raw FCI PID/BLP entries.
        entries: &'a [u8],
    },
    /// Transport-wide congestion control feedback.
    TransportCc {
        /// Packet sender SSRC.
        sender_ssrc: u32,
        /// Media source SSRC.
        media_ssrc: u32,
        /// Raw transport-cc FCI bytes.
        body: &'a [u8],
    },
}

impl RtpFeedback<'_> {
    /// Returns the Stage 1 stability marker for this public API.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::RtpFeedback;
    /// let fb = RtpFeedback::Nack {
    ///     sender_ssrc: 1,
    ///     media_ssrc: 2,
    ///     entries: &[],
    /// };
    /// assert_eq!(fb.stability(), refract_rtp::Stability::Stage1);
    /// ```
    #[must_use]
    pub const fn stability(self) -> Stability {
        Stability::Stage1
    }
}

/// Parsed payload-specific feedback packet.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum PayloadFeedback<'a> {
    /// Picture loss indication.
    Pli {
        /// Packet sender SSRC.
        sender_ssrc: u32,
        /// Media source SSRC.
        media_ssrc: u32,
    },
    /// Full intra request.
    Fir {
        /// Packet sender SSRC.
        sender_ssrc: u32,
        /// Media source SSRC.
        media_ssrc: u32,
        /// Raw FIR FCI bytes.
        entries: &'a [u8],
    },
    /// Receiver estimated maximum bitrate.
    Remb {
        /// Packet sender SSRC.
        sender_ssrc: u32,
        /// Media source SSRC.
        media_ssrc: u32,
        /// Raw REMB FCI bytes.
        body: &'a [u8],
    },
}

impl PayloadFeedback<'_> {
    /// Returns the Stage 1 stability marker for this public API.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::PayloadFeedback;
    /// let feedback = PayloadFeedback::Pli {
    ///     sender_ssrc: 1,
    ///     media_ssrc: 2,
    /// };
    /// assert_eq!(feedback.stability(), refract_rtp::Stability::Stage1);
    /// ```
    #[must_use]
    pub const fn stability(self) -> Stability {
        Stability::Stage1
    }
}

/// Bounded RTCP compound packet generator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RtcpBuilder {
    bytes: [u8; MAX_RTCP_COMPOUND_LEN],
    len: usize,
}

impl RtcpBuilder {
    /// Creates an empty RTCP builder.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::RtcpBuilder;
    /// assert!(RtcpBuilder::new().as_slice().is_empty());
    /// ```
    #[must_use]
    pub const fn new() -> Self {
        Self {
            bytes: [0; MAX_RTCP_COMPOUND_LEN],
            len: 0,
        }
    }

    /// Appends a Sender Report.
    ///
    /// # Errors
    ///
    /// Returns an error if the compound packet would exceed 1500 bytes.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::{RtcpBuilder, SenderReport};
    /// let mut builder = RtcpBuilder::new();
    /// builder.push_sender_report(SenderReport {
    ///     sender_ssrc: 1,
    ///     ntp_msw: 0,
    ///     ntp_lsw: 0,
    ///     rtp_timestamp: 0,
    ///     packet_count: 0,
    ///     octet_count: 0,
    /// })?;
    /// assert_eq!(builder.as_slice()[1], 200);
    /// # Ok::<(), refract_rtp::RtpError>(())
    /// ```
    pub fn push_sender_report(&mut self, sr: SenderReport) -> RtpResult<()> {
        self.reserve_packet(PT_SR, 0, 24, |body| {
            write_u32(&mut body[0..4], sr.sender_ssrc);
            write_u32(&mut body[4..8], sr.ntp_msw);
            write_u32(&mut body[8..12], sr.ntp_lsw);
            write_u32(&mut body[12..16], sr.rtp_timestamp);
            write_u32(&mut body[16..20], sr.packet_count);
            write_u32(&mut body[20..24], sr.octet_count);
        })
    }

    /// Appends a Receiver Report without report blocks.
    ///
    /// # Errors
    ///
    /// Returns an error if the compound packet would exceed 1500 bytes.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::RtcpBuilder;
    /// let mut builder = RtcpBuilder::new();
    /// builder.push_receiver_report(1)?;
    /// assert_eq!(builder.as_slice()[1], 201);
    /// # Ok::<(), refract_rtp::RtpError>(())
    /// ```
    pub fn push_receiver_report(&mut self, sender_ssrc: u32) -> RtpResult<()> {
        self.reserve_packet(PT_RR, 0, 4, |body| write_u32(body, sender_ssrc))
    }

    /// Appends a BYE packet for one SSRC.
    ///
    /// # Errors
    ///
    /// Returns an error if the compound packet would exceed 1500 bytes.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::RtcpBuilder;
    /// let mut builder = RtcpBuilder::new();
    /// builder.push_bye(7)?;
    /// assert_eq!(builder.as_slice()[0] & 0x1f, 1);
    /// # Ok::<(), refract_rtp::RtpError>(())
    /// ```
    pub fn push_bye(&mut self, ssrc: u32) -> RtpResult<()> {
        self.reserve_packet(PT_BYE, 1, 4, |body| write_u32(body, ssrc))
    }

    /// Appends a generic NACK packet.
    ///
    /// # Errors
    ///
    /// Returns an error if the compound packet would exceed 1500 bytes.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::RtcpBuilder;
    /// let mut builder = RtcpBuilder::new();
    /// builder.push_nack(1, 2, 10, 0)?;
    /// assert_eq!(builder.as_slice()[1], 205);
    /// # Ok::<(), refract_rtp::RtpError>(())
    /// ```
    pub fn push_nack(
        &mut self,
        sender_ssrc: u32,
        media_ssrc: u32,
        pid: u16,
        blp: u16,
    ) -> RtpResult<()> {
        self.reserve_packet(PT_RTPFB, FMT_NACK, 12, |body| {
            write_u32(&mut body[0..4], sender_ssrc);
            write_u32(&mut body[4..8], media_ssrc);
            write_u16(&mut body[8..10], pid);
            write_u16(&mut body[10..12], blp);
        })
    }

    /// Appends a PLI packet.
    ///
    /// # Errors
    ///
    /// Returns an error if the compound packet would exceed 1500 bytes.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::RtcpBuilder;
    /// let mut builder = RtcpBuilder::new();
    /// builder.push_pli(1, 2)?;
    /// assert_eq!(builder.as_slice()[0] & 0x1f, 1);
    /// # Ok::<(), refract_rtp::RtpError>(())
    /// ```
    pub fn push_pli(&mut self, sender_ssrc: u32, media_ssrc: u32) -> RtpResult<()> {
        self.reserve_packet(PT_PSFB, FMT_PLI, 8, |body| {
            write_u32(&mut body[0..4], sender_ssrc);
            write_u32(&mut body[4..8], media_ssrc);
        })
    }

    /// Appends a REMB packet with a pre-encoded FCI body.
    ///
    /// # Errors
    ///
    /// Returns an error if the FCI length is not a 32-bit multiple or the
    /// compound packet would exceed 1500 bytes.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::RtcpBuilder;
    /// let mut builder = RtcpBuilder::new();
    /// builder.push_remb(1, 2, b"REMB\0\0\0\0")?;
    /// assert_eq!(builder.as_slice()[1], 206);
    /// # Ok::<(), refract_rtp::RtpError>(())
    /// ```
    pub fn push_remb(&mut self, sender_ssrc: u32, media_ssrc: u32, fci: &[u8]) -> RtpResult<()> {
        let body_len = 8 + fci.len();
        if !body_len.is_multiple_of(4) {
            return Err(RtpError::MalformedRtcp {
                packet_type: PT_PSFB,
                reason: RtcpErrorReason::CountLengthMismatch,
            });
        }
        self.reserve_packet(PT_PSFB, FMT_REMB, body_len, |body| {
            write_u32(&mut body[0..4], sender_ssrc);
            write_u32(&mut body[4..8], media_ssrc);
            body[8..].copy_from_slice(fci);
        })
    }

    /// Returns the generated compound bytes.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::rtcp::RtcpBuilder;
    /// assert!(RtcpBuilder::new().as_slice().is_empty());
    /// ```
    #[must_use]
    pub const fn as_slice(&self) -> &[u8] {
        self.bytes.split_at(self.len).0
    }

    /// Returns the Stage 1 stability marker for this public API.
    ///
    /// # Examples
    ///
    /// ```
    /// # use refract_rtp::{rtcp::RtcpBuilder, Stability};
    /// assert_eq!(RtcpBuilder::new().stability(), Stability::Stage1);
    /// ```
    #[must_use]
    pub const fn stability(&self) -> Stability {
        Stability::Stage1
    }

    fn reserve_packet(
        &mut self,
        packet_type: u8,
        count: u8,
        body_len: usize,
        fill: impl FnOnce(&mut [u8]),
    ) -> RtpResult<()> {
        if !body_len.is_multiple_of(4) {
            return Err(RtpError::MalformedRtcp {
                packet_type,
                reason: RtcpErrorReason::CountLengthMismatch,
            });
        }
        let packet_len = RTCP_HEADER_LEN + body_len;
        let Some(new_len) = self.len.checked_add(packet_len) else {
            return Err(RtpError::RtcpCompoundTooLarge {
                len: usize::MAX,
                max: MAX_RTCP_COMPOUND_LEN,
            });
        };
        if new_len > MAX_RTCP_COMPOUND_LEN {
            return Err(RtpError::RtcpCompoundTooLarge {
                len: new_len,
                max: MAX_RTCP_COMPOUND_LEN,
            });
        }
        let words_minus_one =
            u16::try_from(packet_len / 4 - 1).map_err(|_| RtpError::RtcpCompoundTooLarge {
                len: packet_len,
                max: MAX_RTCP_COMPOUND_LEN,
            })?;
        let start = self.len;
        self.bytes[start] = (RTCP_VERSION << VERSION_SHIFT) | (count & COUNT_MASK);
        self.bytes[start + 1] = packet_type;
        write_u16(&mut self.bytes[start + 2..start + 4], words_minus_one);
        fill(&mut self.bytes[start + RTCP_HEADER_LEN..new_len]);
        self.len = new_len;
        Ok(())
    }
}

impl Default for RtcpBuilder {
    fn default() -> Self {
        Self::new()
    }
}

fn parse_packet(count: u8, packet_type: u8, body: &[u8]) -> RtpResult<RtcpPacket<'_>> {
    match packet_type {
        PT_SR => parse_sr(count, body),
        PT_RR => parse_rr(count, body),
        PT_SDES => Ok(RtcpPacket::Sdes {
            count,
            chunks: body,
        }),
        PT_BYE => Ok(RtcpPacket::Bye { count, body }),
        PT_APP => Ok(RtcpPacket::App {
            subtype: count,
            body,
        }),
        PT_RTPFB => parse_rtpfb(count, body),
        PT_PSFB => parse_psfb(count, body),
        PT_XR => parse_xr(body),
        _ => Err(RtpError::MalformedRtcp {
            packet_type,
            reason: RtcpErrorReason::UnsupportedFeedbackFormat,
        }),
    }
}

fn parse_sr(count: u8, body: &[u8]) -> RtpResult<RtcpPacket<'_>> {
    let needed = 24 + usize::from(count) * 24;
    if body.len() < needed {
        return Err(RtpError::MalformedRtcp {
            packet_type: PT_SR,
            reason: RtcpErrorReason::BodyTooShort,
        });
    }
    Ok(RtcpPacket::SenderReport(SenderReport {
        sender_ssrc: read_u32(&body[0..4]),
        ntp_msw: read_u32(&body[4..8]),
        ntp_lsw: read_u32(&body[8..12]),
        rtp_timestamp: read_u32(&body[12..16]),
        packet_count: read_u32(&body[16..20]),
        octet_count: read_u32(&body[20..24]),
    }))
}

fn parse_rr(count: u8, body: &[u8]) -> RtpResult<RtcpPacket<'_>> {
    let needed = 4 + usize::from(count) * 24;
    if body.len() < needed {
        return Err(RtpError::MalformedRtcp {
            packet_type: PT_RR,
            reason: RtcpErrorReason::BodyTooShort,
        });
    }
    Ok(RtcpPacket::ReceiverReport(ReceiverReport {
        sender_ssrc: read_u32(&body[0..4]),
        reports: &body[4..needed],
    }))
}

fn parse_rtpfb(count: u8, body: &[u8]) -> RtpResult<RtcpPacket<'_>> {
    if body.len() < 8 {
        return Err(RtpError::MalformedRtcp {
            packet_type: PT_RTPFB,
            reason: RtcpErrorReason::BodyTooShort,
        });
    }
    let sender_ssrc = read_u32(&body[0..4]);
    let media_ssrc = read_u32(&body[4..8]);
    match count {
        FMT_NACK => Ok(RtcpPacket::Rtpfb(RtpFeedback::Nack {
            sender_ssrc,
            media_ssrc,
            entries: &body[8..],
        })),
        FMT_TRANSPORT_CC => Ok(RtcpPacket::Rtpfb(RtpFeedback::TransportCc {
            sender_ssrc,
            media_ssrc,
            body: &body[8..],
        })),
        _ => Err(RtpError::MalformedRtcp {
            packet_type: PT_RTPFB,
            reason: RtcpErrorReason::UnsupportedFeedbackFormat,
        }),
    }
}

fn parse_psfb(count: u8, body: &[u8]) -> RtpResult<RtcpPacket<'_>> {
    if body.len() < 8 {
        return Err(RtpError::MalformedRtcp {
            packet_type: PT_PSFB,
            reason: RtcpErrorReason::BodyTooShort,
        });
    }
    let sender_ssrc = read_u32(&body[0..4]);
    let media_ssrc = read_u32(&body[4..8]);
    match count {
        FMT_PLI => Ok(RtcpPacket::Psfb(PayloadFeedback::Pli {
            sender_ssrc,
            media_ssrc,
        })),
        FMT_FIR => Ok(RtcpPacket::Psfb(PayloadFeedback::Fir {
            sender_ssrc,
            media_ssrc,
            entries: &body[8..],
        })),
        FMT_REMB => Ok(RtcpPacket::Psfb(PayloadFeedback::Remb {
            sender_ssrc,
            media_ssrc,
            body: &body[8..],
        })),
        _ => Err(RtpError::MalformedRtcp {
            packet_type: PT_PSFB,
            reason: RtcpErrorReason::UnsupportedPayloadFeedbackFormat,
        }),
    }
}

fn parse_xr(body: &[u8]) -> RtpResult<RtcpPacket<'_>> {
    if body.len() < 4 {
        return Err(RtpError::MalformedRtcp {
            packet_type: PT_XR,
            reason: RtcpErrorReason::BodyTooShort,
        });
    }
    Ok(RtcpPacket::Xr {
        sender_ssrc: read_u32(&body[0..4]),
        blocks: &body[4..],
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builds_and_parses_bye_and_pli() {
        let mut builder = RtcpBuilder::new();
        builder.push_bye(7).expect("bye fits");
        builder.push_pli(1, 2).expect("pli fits");
        let packets = RtcpCompound::parse(builder.as_slice())
            .expect("compound parse")
            .collect::<RtpResult<Vec<_>>>()
            .expect("packets parse");
        assert_eq!(packets.len(), 2);
        assert!(matches!(packets[0], RtcpPacket::Bye { count: 1, .. }));
        assert!(matches!(
            packets[1],
            RtcpPacket::Psfb(PayloadFeedback::Pli {
                sender_ssrc: 1,
                media_ssrc: 2
            })
        ));
    }

    #[test]
    fn rejects_oversized_compound() {
        let oversized = [0_u8; MAX_RTCP_COMPOUND_LEN + 1];
        assert!(matches!(
            RtcpCompound::parse(&oversized),
            Err(RtpError::RtcpCompoundTooLarge { .. })
        ));
    }

    #[test]
    fn parses_sender_report() {
        let sr = SenderReport {
            sender_ssrc: 1,
            ntp_msw: 2,
            ntp_lsw: 3,
            rtp_timestamp: 4,
            packet_count: 5,
            octet_count: 6,
        };
        let mut builder = RtcpBuilder::new();
        builder.push_sender_report(sr).expect("sr fits");
        let packet = RtcpCompound::parse(builder.as_slice())
            .expect("compound parse")
            .next()
            .transpose()
            .expect("packet parse")
            .expect("packet present");
        assert_eq!(packet, RtcpPacket::SenderReport(sr));
    }
}
