[package]
name = "refract-roomstore-redis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
redis-integration = []

[dependencies]
futures-core = "=0.3.32"
redis.workspace = true
refract-core = { path = "../refract-core" }
refract-roomstore = { path = "../refract-roomstore" }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
compio.workspace = true

[lints]
workspace = true
