[package]
name = "refract-rtc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
refract-cc = { path = "../refract-cc" }
refract-core = { path = "../refract-core" }
refract-crypto = { path = "../refract-crypto" }
refract-jitter = { path = "../refract-jitter" }
refract-router = { path = "../refract-router" }
refract-srtp = { path = "../refract-srtp" }
str0m = { version = "=0.20.0", default-features = false, features = ["aws-lc-rs"] }
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
