[package]
name = "refract-router"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
alloc-track = ["dep:refract-slab", "refract-slab/alloc-track"]

[dependencies]
arc-swap.workspace = true
metrics.workspace = true
refract-slab = { path = "../refract-slab", optional = true }
thiserror.workspace = true

[dev-dependencies]
loom.workspace = true

[lints]
workspace = true
